dist: bionic
language: cpp

before_install:
  - sudo apt-get update
  - sudo apt-get -y install cmake libglm-dev libgtest-dev libbenchmark-dev

script:
  - cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release .
  - cmake --build .
  - ./bin/CCLib_Benchmark
  - ./bin/CCLib_Test
