language: cpp
compiler: gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7

script:
      - mkdir build
      - cd build
      - g++-7 ../benchmark/benchmark.cpp -std=c++1z -Ofast -march=native -obenchmark
      - ./benchmark
