language: cpp
compiler: gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-8

script:
  - mkdir build
  - cd build
  - g++-8 ../benchmark/benchmark.cpp -std=c++1z -Ofast -march=native -obenchmark
  - ./benchmark
