dist: focal
language: cpp

before_install:
  - sudo apt-get update
  - sudo apt-get -y install cmake libglm-dev libgtest-dev libbenchmark-dev

script:
  - cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release .
  - cmake --build .
  - if [[ -f ./bin/CCLib_Benchmark ]]; then ./bin/CCLib_Benchmark ; fi
  - if [[ -f ./bin/CCLib_Test ]]; then ./bin/CCLib_Test ; fi
