version: 1.0.{build}

image:
- Visual Studio 2019
- Ubuntu2004

install:
- cmd: >-
    vcpkg install glm:x64-windows benchmark:x64-windows gtest:x64-windows

    vcpkg integrate install


- sh: >-
    sudo apt-get -y install libglm-dev libgtest-dev libbenchmark-dev


cache: c:\tools\vcpkg\installed\


build_script:

- cmd: >-
    mkdir build && cd build

    cmake -DCMAKE_TOOLCHAIN_FILE=C:/Tools/vcpkg/scripts/buildsystems/vcpkg.cmake -G "Visual Studio 16 2019" -DCMAKE_BUILD_TYPE=Release ..
    
    cmake --build . --config Release

    cd ../bin/Release

    .\CCLib_Benchmark.exe

    .\CCLib_Test.exe


- sh: >-
    mkdir build && cd build

    cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release ..
    
    cmake --build . --config Release

    . ../bin/CCLib_Benchmark

    . ../bin/CCLib_Test


test: off